export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const OPEN_POSITION = 'OPEN_POSITION'
export const OPEN_POSITION_RETURNED = 'OPEN_POSITION_RETURNED'

export const GET_DEBT_BALANCES = 'GET_DEBT_BALANCES'
export const DEBT_BALANCES_RETURNED = 'DEBT_BALANCES_RETURNED'

export const REPAY_DEBT = 'REPAY_DEBT'
export const REPAY_DEBT_RETURNED = 'REPAY_DEBT_RETURNED'

export const WITHDRAW_PRINCIPAL = 'WITHDRAW_PRINCIPAL'
export const WITHDRAW_PRINCIPAL_RETURNED = 'WITHDRAW_PRINCIPAL_RETURNED'

export const CLOSE_POSITION = 'CLOSE_POSITION'
export const CLOSE_POSITION_RETURNED = 'CLOSE_POSITION_RETURNED'

export const EXIT_POSITION = 'EXIT_POSITION'
export const EXIT_POSITION_RETURNED = 'EXIT_POSITION_RETURNED'
