export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const OPEN_POSITION = 'OPEN_POSITION'
export const OPEN_POSITION_RETURNED = 'OPEN_POSITION_RETURNED'

export const CLOSE_POSITION = 'CLOSE_POSITION'
export const CLOSE_POSITION_RETURNED = 'CLOSE_POSITION_RETURNED'

export const SETTLE_POSITION = 'SETTLE_POSITION'
export const SETTLE_POSITION_RETURNED = 'SETTLE_POSITION_RETURNED'

export const GET_POSITIONS = 'GET_POSITIONS'
export const POSITIONS_RETURNED = 'GET_POSITIONS_RETURNED'

export const REFRESH_POSITIONS = 'REFRESH_POSITIONS'
export const REFRESH_POSITIONS_RETURNED = 'REFRESH_POSITIONS_RETURNED'
